### PR TITLE
Use standalone template Pretty-print JSON

### PR DESCRIPTION
**Pull request by urre**
- Use standalone template
- Inline plugin specific CSS
- Pretty-print JSON output

Screenshot:

pretty-print

### CODE REVIEW

**Comment by travisspencer** [comment]
Three points of feedback:

1. The jump from the skinnier well to the wider one is a bit jarring. Attributes tend not to be so long, so I'd keep the large skinnier one to avoid the shift in width.

Screenshot 2020-02-22 at 2 49 03 PM
Screenshot 2020-02-22 at 2 49 13 PM

2. The Mac-style buttons in the header don't add much IMO. There's already a heading -- subject attribute and context attributes. The close, minimize, full-screen buttons above the script box aren't the best fit IMO.

3. It would be nice if we also updated the icon in the admin UI for this plugin:

Screenshot 2020-02-22 at 2 44 08 PM

**Comment by urre** [comment]
@travisspencer 

1. We tried the wide one, since the nested json output takes needs some space horisontally. We can use the regular width
2. Yes, I can remove them from here
3. Yes, I'll add one in admin UI

**Comment by urre** [comment]
I've updated the width of the login-well to 800 px instead of 1200 px. 

Skärmavbild 2020-02-25 kl  08 34 12

**Comment by urre** [comment]
@travisspencer I've made a PR for the icon: [https://bitbucket.org/curity/curity-web-ui/pull-requests/881/is-4508-add-icon-for-debug-attribute](https://bitbucket.org/curity/curity-web-ui/pull-requests/881/is-4508-add-icon-for-debug-attribute)

**Comment by travisspencer** [comment]
Looking VERY good, @urre ! Merge away

**Pull request merged**
